#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SampleAndroid.Resource", IsApplication=true)]

namespace SampleAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010005
			public const int adHeight = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int adWidth = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int auto_refresh_interval = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int expands_to_fit_screen_width = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int load_landing_page_in_background = 2130771968;
			
			// aapt resource value: 0x7f010008
			public const int opens_native_browser = 2130771976;
			
			// aapt resource value: 0x7f010001
			public const int placement_id = 2130771969;
			
			// aapt resource value: 0x7f01000a
			public const int resize_ad_to_fit_container = 2130771978;
			
			// aapt resource value: 0x7f010006
			public const int should_reload_on_resume = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int show_loading_indicator = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int test = 2130771971;
			
			// aapt resource value: 0x7f01000c
			public const int transition_direction = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int transition_duration = 2130771981;
			
			// aapt resource value: 0x7f01000b
			public const int transition_type = 2130771979;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int progress = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070013
			public const int MyButton = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int Root = 2131165202;
			
			// aapt resource value: 0x7f07000c
			public const int bar = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int browser_back = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int browser_forward = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int browser_refresh = 2131165201;
			
			// aapt resource value: 0x7f070006
			public const int down = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int fade = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int left = 2131165191;
			
			// aapt resource value: 0x7f07000d
			public const int ll = 2131165197;
			
			// aapt resource value: 0x7f070001
			public const int movein = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int none = 2131165186;
			
			// aapt resource value: 0x7f07000e
			public const int open_browser = 2131165198;
			
			// aapt resource value: 0x7f07000a
			public const int progress_bar = 2131165194;
			
			// aapt resource value: 0x7f070003
			public const int push = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int random = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int reveal = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int right = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int up = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int web_view = 2131165195;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_in_app_browser = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int anjam = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int mraid = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int sdkjs = 2130968578;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06009d
			public const int ApplicationName = 2131099805;
			
			// aapt resource value: 0x7f06009c
			public const int Hello = 2131099804;
			
			// aapt resource value: 0x7f060000
			public const int License = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int action_cant_be_completed = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int adactivity_missing = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int adactivity_no_type = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int adsize_too_big = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int allow = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int already_expanded = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int app_name = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int appid = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int back = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int blank_ad = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int cancel_request = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int console_message = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int conversion_pixel = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int conversion_pixel_delay = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int conversion_pixel_fail = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int conversion_pixel_success = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int create_calendar_event = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int deny = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int destroy_int = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int empty_queue = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int fetch_url = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int fetcher_start_auto = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int fetcher_start_single = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int fire_cb_requester_null = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int fire_cb_result_null = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int first_opensdk_launch = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int forward = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int found_n_in_xml = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int fullscreen_video_hide_error = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int fullscreen_video_show_error = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int get_ad_listener = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int get_allowed_sizes = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int get_auto_refresh = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int get_bg = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int get_gender = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int get_height = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int get_max_height = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int get_max_width = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int get_opens_native_browser = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int get_override_max_size = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int get_period = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int get_placement_id = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int get_should_resume = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int get_width = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int handler_message_pass = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int hidden = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int html5_geo_permission_prompt = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int html5_geo_permission_prompt_title = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int http_bad_status = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int http_io = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int http_timeout = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int http_unknown = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int http_unreachable = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int ignoring_url = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int init = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int instance_exception = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int instantiating_class = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int js_alert = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int load_ad_int = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int loading = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int making_adman = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int max_size_not_set = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int mediated_no_ads = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int mediated_request = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int mediated_request_error = 2131099713;
			
			// aapt resource value: 0x7f060042
			public const int mediated_request_exception = 2131099714;
			
			// aapt resource value: 0x7f060043
			public const int mediated_request_null_activity = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int mediated_view_null = 2131099716;
			
			// aapt resource value: 0x7f060045
			public const int mediation_adding_invalid = 2131099717;
			
			// aapt resource value: 0x7f060046
			public const int mediation_finish = 2131099718;
			
			// aapt resource value: 0x7f060047
			public const int mediation_instantiation_failure = 2131099719;
			
			// aapt resource value: 0x7f060048
			public const int mediation_timeout = 2131099720;
			
			// aapt resource value: 0x7f060049
			public const int moot_restart = 2131099721;
			
			// aapt resource value: 0x7f06004a
			public const int native_tag = 2131099722;
			
			// aapt resource value: 0x7f06004b
			public const int new_ad_since = 2131099723;
			
			// aapt resource value: 0x7f06004c
			public const int new_adview = 2131099724;
			
			// aapt resource value: 0x7f06004d
			public const int no_connectivity = 2131099725;
			
			// aapt resource value: 0x7f06004e
			public const int no_identification = 2131099726;
			
			// aapt resource value: 0x7f06004f
			public const int no_response = 2131099727;
			
			// aapt resource value: 0x7f060050
			public const int no_size_info = 2131099728;
			
			// aapt resource value: 0x7f060051
			public const int no_user_interaction = 2131099729;
			
			// aapt resource value: 0x7f060052
			public const int not_first_opensdk_launch = 2131099730;
			
			// aapt resource value: 0x7f060053
			public const int number_format = 2131099731;
			
			// aapt resource value: 0x7f060054
			public const int open_browser = 2131099732;
			
			// aapt resource value: 0x7f060055
			public const int opening_app_store = 2131099733;
			
			// aapt resource value: 0x7f060056
			public const int opening_inapp = 2131099734;
			
			// aapt resource value: 0x7f060057
			public const int opening_native = 2131099735;
			
			// aapt resource value: 0x7f060058
			public const int opening_native_current = 2131099736;
			
			// aapt resource value: 0x7f060059
			public const int opening_url = 2131099737;
			
			// aapt resource value: 0x7f06005a
			public const int opening_url_failed = 2131099738;
			
			// aapt resource value: 0x7f06005b
			public const int permissions_internet = 2131099739;
			
			// aapt resource value: 0x7f06005c
			public const int permissions_missing_location = 2131099740;
			
			// aapt resource value: 0x7f06005d
			public const int permissions_missing_network_state = 2131099741;
			
			// aapt resource value: 0x7f06005e
			public const int placement_id = 2131099742;
			
			// aapt resource value: 0x7f06005f
			public const int play_vide_no_uri = 2131099743;
			
			// aapt resource value: 0x7f060060
			public const int refresh = 2131099744;
			
			// aapt resource value: 0x7f060061
			public const int request_delayed_by_x_ms = 2131099745;
			
			// aapt resource value: 0x7f060062
			public const int request_parameter_override_attempt = 2131099746;
			
			// aapt resource value: 0x7f060063
			public const int resize = 2131099747;
			
			// aapt resource value: 0x7f060064
			public const int response_blank = 2131099748;
			
			// aapt resource value: 0x7f060065
			public const int response_body = 2131099749;
			
			// aapt resource value: 0x7f060066
			public const int response_error = 2131099750;
			
			// aapt resource value: 0x7f060067
			public const int response_header = 2131099751;
			
			// aapt resource value: 0x7f060068
			public const int response_json_error = 2131099752;
			
			// aapt resource value: 0x7f060069
			public const int response_no_ads = 2131099753;
			
			// aapt resource value: 0x7f06006a
			public const int result_cb_bad_response = 2131099754;
			
			// aapt resource value: 0x7f06006b
			public const int result_cb_ignored = 2131099755;
			
			// aapt resource value: 0x7f06006c
			public const int screen_off_stop = 2131099756;
			
			// aapt resource value: 0x7f06006d
			public const int screen_on_start = 2131099757;
			
			// aapt resource value: 0x7f06006e
			public const int set_ad_listener = 2131099758;
			
			// aapt resource value: 0x7f06006f
			public const int set_allowed_sizes = 2131099759;
			
			// aapt resource value: 0x7f060070
			public const int set_auto_refresh = 2131099760;
			
			// aapt resource value: 0x7f060071
			public const int set_bg = 2131099761;
			
			// aapt resource value: 0x7f060072
			public const int set_gender = 2131099762;
			
			// aapt resource value: 0x7f060073
			public const int set_height = 2131099763;
			
			// aapt resource value: 0x7f060074
			public const int set_max_size = 2131099764;
			
			// aapt resource value: 0x7f060075
			public const int set_opens_native_browser = 2131099765;
			
			// aapt resource value: 0x7f060076
			public const int set_orientation_properties = 2131099766;
			
			// aapt resource value: 0x7f060077
			public const int set_override_max_size = 2131099767;
			
			// aapt resource value: 0x7f060078
			public const int set_period = 2131099768;
			
			// aapt resource value: 0x7f060079
			public const int set_placement_id = 2131099769;
			
			// aapt resource value: 0x7f06007a
			public const int set_should_resume = 2131099770;
			
			// aapt resource value: 0x7f06007b
			public const int set_size = 2131099771;
			
			// aapt resource value: 0x7f06007c
			public const int set_width = 2131099772;
			
			// aapt resource value: 0x7f06007d
			public const int show_int = 2131099773;
			
			// aapt resource value: 0x7f06007e
			public const int show_loading_indicator_xml = 2131099774;
			
			// aapt resource value: 0x7f06007f
			public const int start = 2131099775;
			
			// aapt resource value: 0x7f060080
			public const int stop = 2131099776;
			
			// aapt resource value: 0x7f060081
			public const int store_picture_accept = 2131099777;
			
			// aapt resource value: 0x7f060082
			public const int store_picture_decline = 2131099778;
			
			// aapt resource value: 0x7f060083
			public const int store_picture_error = 2131099779;
			
			// aapt resource value: 0x7f060084
			public const int store_picture_message = 2131099780;
			
			// aapt resource value: 0x7f060085
			public const int store_picture_title = 2131099781;
			
			// aapt resource value: 0x7f060086
			public const int too_old = 2131099782;
			
			// aapt resource value: 0x7f060087
			public const int transition_direction = 2131099783;
			
			// aapt resource value: 0x7f060088
			public const int transition_duration = 2131099784;
			
			// aapt resource value: 0x7f060089
			public const int transition_type = 2131099785;
			
			// aapt resource value: 0x7f06008a
			public const int ua = 2131099786;
			
			// aapt resource value: 0x7f06008b
			public const int unhidden = 2131099787;
			
			// aapt resource value: 0x7f06008c
			public const int unknown_exception = 2131099788;
			
			// aapt resource value: 0x7f06008d
			public const int unsupported_encoding = 2131099789;
			
			// aapt resource value: 0x7f06008e
			public const int unsupported_mraid = 2131099790;
			
			// aapt resource value: 0x7f06008f
			public const int webclient_error = 2131099791;
			
			// aapt resource value: 0x7f060090
			public const int webview_loading = 2131099792;
			
			// aapt resource value: 0x7f060091
			public const int webview_received_error = 2131099793;
			
			// aapt resource value: 0x7f060092
			public const int xml_ad_height = 2131099794;
			
			// aapt resource value: 0x7f060093
			public const int xml_ad_width = 2131099795;
			
			// aapt resource value: 0x7f060094
			public const int xml_load_landing_page_in_background = 2131099796;
			
			// aapt resource value: 0x7f060095
			public const int xml_resize_ad_to_fit_container = 2131099797;
			
			// aapt resource value: 0x7f060096
			public const int xml_set_auto_refresh = 2131099798;
			
			// aapt resource value: 0x7f060097
			public const int xml_set_expands_to_full_screen_width = 2131099799;
			
			// aapt resource value: 0x7f060098
			public const int xml_set_opens_native_browser = 2131099800;
			
			// aapt resource value: 0x7f060099
			public const int xml_set_period = 2131099801;
			
			// aapt resource value: 0x7f06009a
			public const int xml_set_should_reload = 2131099802;
			
			// aapt resource value: 0x7f06009b
			public const int xml_set_test = 2131099803;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppBaseTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int AppTheme = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] BannerAdView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 5
			public const int BannerAdView_adHeight = 5;
			
			// aapt resource value: 4
			public const int BannerAdView_adWidth = 4;
			
			// aapt resource value: 7
			public const int BannerAdView_auto_refresh_interval = 7;
			
			// aapt resource value: 9
			public const int BannerAdView_expands_to_fit_screen_width = 9;
			
			// aapt resource value: 0
			public const int BannerAdView_load_landing_page_in_background = 0;
			
			// aapt resource value: 8
			public const int BannerAdView_opens_native_browser = 8;
			
			// aapt resource value: 1
			public const int BannerAdView_placement_id = 1;
			
			// aapt resource value: 10
			public const int BannerAdView_resize_ad_to_fit_container = 10;
			
			// aapt resource value: 6
			public const int BannerAdView_should_reload_on_resume = 6;
			
			// aapt resource value: 2
			public const int BannerAdView_show_loading_indicator = 2;
			
			// aapt resource value: 3
			public const int BannerAdView_test = 3;
			
			// aapt resource value: 12
			public const int BannerAdView_transition_direction = 12;
			
			// aapt resource value: 13
			public const int BannerAdView_transition_duration = 13;
			
			// aapt resource value: 11
			public const int BannerAdView_transition_type = 11;
			
			public static int[] InterstitialAdView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771976};
			
			// aapt resource value: 0
			public const int InterstitialAdView_load_landing_page_in_background = 0;
			
			// aapt resource value: 4
			public const int InterstitialAdView_opens_native_browser = 4;
			
			// aapt resource value: 1
			public const int InterstitialAdView_placement_id = 1;
			
			// aapt resource value: 2
			public const int InterstitialAdView_show_loading_indicator = 2;
			
			// aapt resource value: 3
			public const int InterstitialAdView_test = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
